from __future__ import annotations

import json
import uuid
from pathlib import Path

import numpy as np
import trimesh
from fastapi import HTTPException

from .files import public_url
from .schemas import BodyMeasurements, BodyModelResult
from .settings import settings
from .store import body_models


MEASUREMENT_ORDER = [
    "weight", "height", "neck", "bust", "waist", "hip", "arm_length",
    "crotch_to_floor", "shoulder", "back_length", "natural_waist", "max_hip",
    "waist_rise", "hand_length", "upper_arm", "wrist", "leg_length", "knee", "thigh",
]


class AnthropometricBodyService:
    """Modern runtime adapter for 3D-Human-Body-Shape local-RFE matrices.

    A prediction reconstructs every vertex of a single template mesh. No limb or bone
    is scaled independently, so weight cannot lengthen the model and hip/thigh/knee
    transitions remain topologically continuous.
    """

    def __init__(self, model_dir: Path):
        self.model_dir = model_dir
        self.matrix_path = model_dir / "female_rfe.npz"
        self.template_path = model_dir / "female_template.obj"
        self.available = self.matrix_path.exists() and self.template_path.exists()
        if self.available:
            payload = np.load(self.matrix_path, allow_pickle=False)
            self.mean = payload["mean"]
            self.components = payload["components"]
            self.coef = payload["coef"]
            self.intercept = payload["intercept"]
            self.measurement_mean = payload.get("measurement_mean", np.zeros(19))
            self.template = trimesh.load(self.template_path, process=False)

    @staticmethod
    def complete(m: BodyMeasurements, means: np.ndarray) -> dict[str, float]:
        raw = m.model_dump()
        aliases = {
            "max_hip": raw["hip"], "natural_waist": raw.get("natural_waist") or raw["waist"],
            "thigh": raw.get("thigh"), "knee": raw.get("knee"), "wrist": raw.get("wrist"),
            "upper_arm": raw.get("upper_arm"), "leg_length": raw.get("leg_length"),
        }
        result = {**raw, **aliases}
        # Deterministic anthropometric priors for optional fields. Production matrices
        # may supply training-set means; these estimates are returned for transparency.
        bmi = raw["weight"] / (raw["height"] / 100) ** 2
        result.setdefault("arm_length", raw["height"] * .445)
        result.setdefault("crotch_to_floor", raw["height"] * .47)
        result.setdefault("back_length", raw["height"] * .255)
        result.setdefault("waist_rise", raw["height"] * .155)
        result.setdefault("hand_length", raw["height"] * .105)
        result["neck"] = result.get("neck") or 30 + max(0, bmi - 18) * .32
        result["upper_arm"] = result.get("upper_arm") or 22 + max(0, bmi - 18) * .55
        result["wrist"] = result.get("wrist") or raw["height"] * .095
        result["leg_length"] = result.get("leg_length") or raw["height"] * .58
        result["knee"] = result.get("knee") or 31 + max(0, bmi - 18) * .35
        result["thigh"] = result.get("thigh") or 43 + max(0, bmi - 18) * 1.05
        return {k: float(v) for k, v in result.items() if v is not None}

    def generate(self, measurements: BodyMeasurements) -> BodyModelResult:
        if not self.available:
            raise HTTPException(
                503,
                detail={
                    "code": "body_model_unavailable",
                    "message": "人体回归权重尚未部署；已停止使用会骨肉分离的分段假模型。",
                },
            )
        completed = self.complete(measurements, self.measurement_mean)
        vector = np.array([completed.get(k, self.measurement_mean[i]) for i, k in enumerate(MEASUREMENT_ORDER)])
        vector[0] = np.cbrt(vector[0]) * 1000.0
        vector[1:] *= 10.0
        latent = vector @ self.coef.T + self.intercept
        vertices = (latent @ self.components + self.mean).reshape((-1, 3))
        if not np.isfinite(vertices).all() or len(vertices) != len(self.template.vertices):
            raise HTTPException(422, detail={"code": "invalid_mesh", "message": "人体参数生成了无效网格。"})

        body_id = uuid.uuid4().hex
        out_dir = settings.data_dir / "body-models" / body_id
        out_dir.mkdir(parents=True, exist_ok=True)
        mesh = trimesh.Trimesh(vertices=vertices, faces=self.template.faces, process=False)
        glb_path = out_dir / "body.glb"
        glb_path.write_bytes(mesh.export(file_type="glb"))
        # Reference renders are generated by the rendering worker in production.
        metadata = {
            "id": body_id,
            "measurements": completed,
            "glb_url": public_url(glb_path),
            "front_reference_url": "",
            "three_quarter_reference_url": "",
        }
        (out_dir / "profile.json").write_text(json.dumps(metadata, ensure_ascii=False), "utf-8")
        body_models.put(body_id, metadata)
        return BodyModelResult(body_model_id=body_id, completed_measurements=completed, glb_url=metadata["glb_url"], front_reference_url="", three_quarter_reference_url="", warnings=["参考照渲染任务尚在处理"])


body_service = AnthropometricBodyService(settings.model_dir)

